
networks:
  dev-network:
    driver: bridge

services:

  dev-db:
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    working_dir: /code
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - dev-db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

name: ninjafastapi-development