"""initial

Revision ID: 0345a04f0865
Revises:
Create Date: 2025-04-20 14:18:21.077676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0345a04f0865"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ninja",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("clan", sa.String(length=20), nullable=False),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("experience", sa.Integer(), nullable=True),
        sa.Column("sensei", sa.String(length=20), nullable=True),
        sa.Column("summon_animal", sa.String(length=20), nullable=True),
        sa.Column("mission_completed", sa.Integer(), nullable=True),
        sa.Column(
            "rank",
            sa.Enum(
                "academy", "genin", "chunin", "jonin", "anbu", "kage", name="rankenum"
            ),
            nullable=True,
        ),
        sa.Column(
            "kekkei_genkai",
            sa.Enum(
                "sharingan",
                "byakugan",
                "rinnegan",
                "wood_release",
                "none",
                name="kekkeigenkaienum",
            ),
            nullable=True,
        ),
        sa.Column("chakra_nature", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("alive", sa.Boolean(), nullable=True),
        sa.Column("forbidden", sa.Boolean(), nullable=True),
        sa.Column(
            "jinchuriki",
            sa.Enum(
                "shukaku",
                "matatabi",
                "isobu",
                "son_goku",
                "kokuo",
                "saiken",
                "choumei",
                "gyuki",
                "kurama",
                "juubi",
                "none",
                name="jinchurikienum",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ninja")
    # ### end Alembic commands ###
