"""initial

Revision ID: 460adc89e7b8
Revises: add9c8aa3fde
Create Date: 2025-04-21 11:51:36.868640

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "460adc89e7b8"
down_revision: Union[str, None] = "add9c8aa3fde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ninja",
        "rank",
        existing_type=postgresql.ENUM(
            "academy", "genin", "chunin", "jonin", "anbu", "kage", name="rankenum"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ninja",
        "rank",
        existing_type=postgresql.ENUM(
            "academy", "genin", "chunin", "jonin", "anbu", "kage", name="rankenum"
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
