"""initial

Revision ID: 86694ae55120
Revises: 460adc89e7b8
Create Date: 2025-04-21 11:52:32.690292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "86694ae55120"
down_revision: Union[str, None] = "460adc89e7b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ninja", "alive", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("ninja", "forbidden", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "ninja",
        "jinchuriki",
        existing_type=postgresql.ENUM(
            "shukaku",
            "matatabi",
            "isobu",
            "son_goku",
            "kokuo",
            "saiken",
            "choumei",
            "gyuki",
            "kurama",
            "juubi",
            "none",
            name="jinchurikienum",
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ninja",
        "jinchuriki",
        existing_type=postgresql.ENUM(
            "shukaku",
            "matatabi",
            "isobu",
            "son_goku",
            "kokuo",
            "saiken",
            "choumei",
            "gyuki",
            "kurama",
            "juubi",
            "none",
            name="jinchurikienum",
        ),
        nullable=True,
    )
    op.alter_column("ninja", "forbidden", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("ninja", "alive", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
