"""initial

Revision ID: add9c8aa3fde
Revises: 5bc79ea33e94
Create Date: 2025-04-21 11:50:09.587846

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "add9c8aa3fde"
down_revision: Union[str, None] = "5bc79ea33e94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ninja", "level", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("ninja", "experience", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "ninja", "mission_completed", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ninja", "mission_completed", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("ninja", "experience", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("ninja", "level", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
