"""initial

Revision ID: ae3242d2d9e1
Revises:
Create Date: 2025-04-22 22:09:50.469374

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ae3242d2d9e1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ninja",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("clan", sa.String(length=20), nullable=False),
        sa.Column("level", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "experience", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("sensei", sa.String(length=20), nullable=True),
        sa.Column("summon_animal", sa.String(length=20), nullable=True),
        sa.Column(
            "mission_completed",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "rank",
            sa.Enum(
                "academy", "genin", "chunin", "jonin", "anbu", "kage", name="rankenum"
            ),
            server_default=sa.text("'academy'"),
            nullable=False,
        ),
        sa.Column(
            "kekkei_genkai",
            sa.Enum(
                "sharingan",
                "byakugan",
                "rinnegan",
                "wood_release",
                "none",
                name="kekkeigenkaienum",
            ),
            server_default=sa.text("'none'"),
            nullable=True,
        ),
        sa.Column("chakra_nature", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "alive", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "forbidden", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "jinchuriki",
            sa.Enum(
                "shukaku",
                "matatabi",
                "isobu",
                "son_goku",
                "kokuo",
                "saiken",
                "choumei",
                "gyuki",
                "kurama",
                "juubi",
                "none",
                name="jinchurikienum",
            ),
            server_default=sa.text("'none'"),
            nullable=False,
        ),
        sa.CheckConstraint("LENGTH(clan) > 0", name="clan_length_check"),
        sa.CheckConstraint("LENGTH(name) > 0", name="name_length_check"),
        sa.CheckConstraint("experience >= 0", name="experience_positive_check"),
        sa.CheckConstraint("level >= 1", name="min_1_lvl_check"),
        sa.CheckConstraint("mission_completed >= 0", name="mission_positive_check"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ninja")
    # ### end Alembic commands ###
