"""add avatar filename to user

Revision ID: e6b5c70606b7
Revises: a152da4826f0
Create Date: 2026-04-06 18:42:22.543652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b5c70606b7'
down_revision: Union[str, None] = 'a152da4826f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'team', 'ninja', ['sensei_id'], ['id'], use_alter=True)
    op.add_column('user', sa.Column('avatar_filename', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'village', 'ninja', ['kage_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'village', type_='foreignkey')
    op.drop_column('user', 'avatar_filename')
    op.drop_constraint(None, 'team', type_='foreignkey')
    # ### end Alembic commands ###
