name: Checks

on: [push, pull_request]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Black format check
        run: docker compose run --rm app sh -c "black --check ."

      - name: Ruff lint check
        run: docker compose run --rm app sh -c "ruff check ."
