name: Checks

on: [push, pull_request]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Black format check
        run: docker compose run --rm app sh -c "black --check ."

      - name: Ruff lint check
        run: docker compose run --rm app sh -c "ruff check ."
